name: Build Release Zip

on:
  push:
    tags:
      - 'v*'

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare plugin folder
        run: |
          mkdir bono-arm-api
          cp -r *.php readme.txt LICENSE bono-arm-api/

      - name: Zip it
        run: zip -r bono-arm-api.zip bono-arm-api

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: bono-arm-api.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

